version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: TentRental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
